# Generated by Django 5.1.3 on 2024-11-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado_envio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id_tipo_cliente', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePago',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('detalle_adicional', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('capacidad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id_guia', models.AutoField(primary_key=True, serialize=False)),
                ('id_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.envio')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='id_guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.guia'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_ejecucion', models.DateField()),
                ('costo', models.FloatField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_despacho', models.CharField(max_length=255)),
                ('direccion_embarque', models.CharField(max_length=255)),
                ('numero_guia', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.servicio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.tipocliente'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.factura')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.tipodepago')),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_transportista', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('id_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('dimensiones', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('id_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.envio')),
                ('id_transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.transportista')),
            ],
        ),
        migrations.AddField(
            model_name='guia',
            name='id_transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.transportista'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.zona'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_zona_despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona_despacho', to='moniweb.zona'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_zona_embarque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona_embarque', to='moniweb.zona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moniweb.zona'),
        ),
    ]
