# Generated by Django 5.1.3 on 2024-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='envio',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='id_tipo_cliente',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipodepago',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='id_transportista',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zona',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
