# Generated by Django 5.1.3 on 2024-11-16 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniweb', '0002_alter_ciudad_id_alter_cliente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='id_guia',
        ),
        migrations.RemoveField(
            model_name='tipodepago',
            name='detalle_adicional',
        ),
        migrations.AddField(
            model_name='pago',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moniweb.cliente'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_zona_despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_despacho', to='moniweb.zona'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_zona_embarque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_embarque', to='moniweb.zona'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='id_tipo_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipodepago',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='id_transportista',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zona',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Guia',
        ),
    ]
