# Generated by Django 5.1.3 on 2024-11-16 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniweb', '0004_pago_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='id_servicio',
        ),
        migrations.AddField(
            model_name='envio',
            name='id_factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moniweb.factura'),
        ),
    ]
